/*
Visier Authentication APIs

Visier APIs for generating authentication tokens

The version of the OpenAPI document: 22222222.99201.1200


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/

import { AxiosRequestConfig } from "axios";
import {
  AuthenticationApi,
} from "./api";
import { Configuration, ConfigurationParameters } from "./configuration";
import { VisierAuthenticationCustom } from "./client-custom";

export class VisierAuthentication extends VisierAuthenticationCustom {
  readonly authentication: AuthenticationApi;

  constructor(configurationParameters: ConfigurationParameters = {}) {
    super(configurationParameters);
    const configuration = new Configuration(configurationParameters);
    this.authentication = new AuthenticationApi(configuration);
  }

}
