/*
Visier Authentication APIs

Visier APIs for generating authentication tokens

The version of the OpenAPI document: 22222222.99201.1200


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { GoogleProtobufAny } from './google-protobuf-any';

/**
 * The response structure for errors.
 * @export
 * @interface Status
 */
export interface Status {
    /**
     * The status code, which should be an enum value of [google.rpc.Code][google.rpc.Code].
     * @type {number}
     * @memberof Status
     */
    'code'?: number;
    /**
     * The error message returned by the server.
     * @type {string}
     * @memberof Status
     */
    'message'?: string;
    /**
     * A list of messages that carry the error details.  There is a common set of message types for APIs to use.
     * @type {Array<GoogleProtobufAny>}
     * @memberof Status
     */
    'details'?: Array<GoogleProtobufAny>;
}

