/*
Visier Authentication APIs

Visier APIs for generating authentication tokens

The version of the OpenAPI document: 22222222.99201.1200


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Token request body definition.
 * @export
 * @interface TokenRequestBody
 */
export interface TokenRequestBody {
    /**
     * The grant type. Supported values: - `authorization_code`: The authorization code grant type. - `password`: The password grant type. - `urn:visier:params:oauth:grant-type:asid-token`: The ASID token grant type.
     * @type {string}
     * @memberof TokenRequestBody
     */
    'grant_type'?: string;
    /**
     * The ID of the pre-registered client application.
     * @type {string}
     * @memberof TokenRequestBody
     */
    'client_id'?: string;
    /**
     * The optional URI to redirect to after authorization.
     * @type {string}
     * @memberof TokenRequestBody
     */
    'redirect_uri'?: string;
    /**
     * The authorization code. Applicable only for authorization code grant type.
     * @type {string}
     * @memberof TokenRequestBody
     */
    'code'?: string;
    /**
     * The username of the user to authenticate. Applicable only for password grant type.
     * @type {string}
     * @memberof TokenRequestBody
     */
    'username'?: string;
    /**
     * The password of the user to authenticate. Applicable only for password grant type.
     * @type {string}
     * @memberof TokenRequestBody
     */
    'password'?: string;
    /**
     * The ASID token. Applicable only for ASID token grant type.
     * @type {string}
     * @memberof TokenRequestBody
     */
    'asid_token'?: string;
}

